import { mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { drivePath } from '@deepseek-ai/dsh-network-drive/identity'
import { expect, it } from 'vitest'
import { DriveAddressing } from '../src/addressing.ts'
import { DriveTransfer } from '../src/transfer.ts'
import { STATE_DIRECTORY } from '../src/materialization.ts'
import { bootWebDav } from './webdav-server.ts'

it('hydrates, merges local entries and rejects stale replacement through the real WebDAV composition', async () => {
  const { ctx, workspace, remote } = await bootWebDav()
  await writeFile(join(remote, 'report.txt'), 'before\n')
  await writeFile(join(workspace, 'local.txt'), 'local\n')
  const target = await ctx.fs.resolve('report.txt')
  await expect(ctx.fs.readText(target)).resolves.toBe('before\n')
  await expect(readFile(join(workspace, 'report.txt'), 'utf8')).resolves.toBe('before\n')
  expect(ctx.sandboxPolicy.workspaceRoot).toBe(workspace)
  const before = await ctx.fs.stat(target)
  expect(before).toMatchObject({ type: 'file', size: 7 })
  if (before === undefined) throw new Error('remote revision was not observed')
  const listed = await ctx.fs.listDir(await ctx.fs.resolve('.'))
  expect(listed.map(entry => entry.name)).toEqual(['local.txt', 'report.txt'])
  const updated = await ctx.fs.writeText(target, 'after\n', { kind: 'replaceIfVersion', version: before.version })
  expect(updated).toMatchObject({ operation: 'update', before: 'before\n', after: 'after\n' })
  await expect(readFile(join(remote, 'report.txt'), 'utf8')).resolves.toBe('after\n')
  await expect(readFile(join(workspace, 'report.txt'), 'utf8')).resolves.toBe('after\n')
  await expect(ctx.fs.writeText(target, 'stale', { kind: 'replaceIfVersion', version: before.version }))
    .rejects.toMatchObject({ code: 'FS_STALE_VERSION' })
  await expect(readFile(join(remote, 'report.txt'), 'utf8')).resolves.toBe('after\n')
  const nested = await ctx.fs.resolve('nested/new.txt')
  await expect(ctx.fs.writeText(nested, 'created', { kind: 'createIfAbsent' })).resolves.toMatchObject({ operation: 'create' })
  await expect(readFile(join(remote, 'nested/new.txt'), 'utf8')).resolves.toBe('created')
})

it('serves local directories and reports native metadata failures after an actual remote miss', async () => {
  const { ctx, workspace, remote } = await bootWebDav()
  await mkdir(join(workspace, 'local'))
  await writeFile(join(workspace, 'local/file'), 'local')
  await symlink('cycle', join(workspace, 'cycle'), 'dir')
  const local = await ctx.fs.resolve('local')
  await expect(ctx.fs.stat(local)).resolves.toMatchObject({ type: 'directory' })
  const listed = await ctx.fs.listDir(local)
  expect(listed.map(entry => entry.name)).toEqual(['file'])
  await expect(ctx.fs.readText(local)).rejects.toMatchObject({ code: 'FS_NOT_REGULAR_FILE' })
  await mkdir(join(remote, 'remote-directory'))
  await expect(ctx.fs.readText(await ctx.fs.resolve('remote-directory'))).rejects.toMatchObject({ code: 'FS_NOT_REGULAR_FILE' })
  await expect(ctx.fs.readText(await ctx.fs.resolve('absent'))).rejects.toMatchObject({ code: 'FS_NOT_FOUND' })
  const cycle = await ctx.fs.resolve('cycle/child')
  await expect(ctx.fs.stat(cycle)).rejects.toMatchObject({ code: 'FS_IO_ERROR', cause: { code: 'ELOOP' } })
  await expect(ctx.fs.writeText(cycle, 'blocked', { kind: 'createIfAbsent' }))
    .rejects.toMatchObject({ code: 'FS_IO_ERROR', cause: { code: 'ELOOP' } })
})

it('closes streamed reads on early completion and consumer failure', async () => {
  const { ctx, remote } = await bootWebDav()
  await writeFile(join(remote, 'stream.txt'), 'line\n'.repeat(40_000))
  const target = await ctx.fs.resolve('stream.txt')
  const stream = await ctx.fs.streamText(target)
  const first = stream[Symbol.asyncIterator]()
  expect(await first.next()).toMatchObject({ done: false })
  if (first.return === undefined) throw new Error('stream does not release early readers')
  await expect(first.return()).resolves.toMatchObject({ done: true })
  await expect(first.next()).resolves.toMatchObject({ done: true })
  const second = stream[Symbol.asyncIterator]()
  expect(await second.next()).toMatchObject({ done: false })
  if (second.throw === undefined) throw new Error('stream does not handle consumer failure')
  const failure = new Error('consumer stopped')
  await expect(second.throw(failure)).rejects.toBe(failure)
  await expect(second.next()).resolves.toMatchObject({ done: true })
  const controller = new AbortController()
  const cancellable = await ctx.fs.streamText(target, controller.signal)
  const third = cancellable[Symbol.asyncIterator]()
  expect(await third.next()).toMatchObject({ done: false })
  controller.abort()
  await expect(third.next()).rejects.toMatchObject({ code: 'FS_ABORTED' })
  await expect(third.next()).resolves.toMatchObject({ done: true })
})

it('keeps the remote file intact when obtaining the edit basis fails locally', async () => {
  const { ctx, workspace, remote } = await bootWebDav()
  await mkdir(join(remote, 'nested'))
  await writeFile(join(remote, 'nested/file'), 'server content')
  await writeFile(join(workspace, 'nested'), 'local obstruction')
  const target = await ctx.fs.resolve('nested/file')
  await expect(ctx.fs.writeText(target, 'replacement')).rejects.toMatchObject({ code: 'FS_IO_ERROR', cause: { code: 'ENOTDIR' } })
  await expect(readFile(join(remote, 'nested/file'), 'utf8')).resolves.toBe('server content')
  await expect(readFile(join(workspace, 'nested'), 'utf8')).resolves.toBe('local obstruction')
})

it('rejects a remote file that grows beyond the transfer ceiling after metadata was read', async () => {
  const { ctx, workspace, remote } = await bootWebDav()
  await writeFile(join(remote, 'growing'), 'x')
  const config = { materializationRoot: workspace, remoteRoot: drivePath(''), maxFileBytes: 4 }
  const addressing = new DriveAddressing(config, () => ctx.networkDrive)
  const transfer = new DriveTransfer(config, addressing, () => ctx.networkDrive)
  const target = addressing.targetFor(drivePath('growing'))
  const observed = await addressing.placementOf(target, undefined)
  expect(observed).toMatchObject({ kind: 'drive', remote: { size: 1 } })
  await writeFile(join(remote, 'growing'), 'now larger')
  await expect(transfer.hydrated(target, 'read', undefined, observed)).rejects.toMatchObject({ code: 'FS_TOO_LARGE' })
  await expect(readFile(join(workspace, 'growing'))).rejects.toMatchObject({ code: 'ENOENT' })
})

it('reports remote directory creation failure without replacing the obstructing file', async () => {
  const { ctx, remote } = await bootWebDav()
  await writeFile(join(remote, 'parent'), 'retained')
  const target = await ctx.fs.resolve('parent/nested/file')
  await expect(ctx.fs.writeText(target, 'new', { kind: 'createIfAbsent' }))
    .rejects.toMatchObject({ code: 'FS_IO_ERROR', cause: { code: 'DRIVE_IO_ERROR' } })
  await expect(readFile(join(remote, 'parent'), 'utf8')).resolves.toBe('retained')
})

it('reports a local publication failure after the remote commit and recovers the committed bytes', async () => {
  const { ctx, workspace, remote } = await bootWebDav()
  const state = join(workspace, STATE_DIRECTORY)
  await writeFile(state, 'local obstruction')
  const target = await ctx.fs.resolve('committed.txt')
  await expect(ctx.fs.writeText(target, 'committed', { kind: 'createIfAbsent' })).rejects.toMatchObject({ code: 'FS_IO_ERROR' })
  await expect(readFile(join(remote, 'committed.txt'), 'utf8')).resolves.toBe('committed')
  await expect(readFile(join(workspace, 'committed.txt'))).rejects.toMatchObject({ code: 'ENOENT' })
  await expect(readFile(state, 'utf8')).resolves.toBe('local obstruction')
  await rm(state)
  await expect(ctx.fs.readText(target)).resolves.toBe('committed')
  await expect(readFile(join(workspace, 'committed.txt'), 'utf8')).resolves.toBe('committed')
})

it('propagates disappearance of local content after its placement was observed', async () => {
  const { ctx, workspace, remote } = await bootWebDav()
  const config = { materializationRoot: workspace, remoteRoot: drivePath(''), maxFileBytes: 1024 }
  const addressing = new DriveAddressing(config, () => ctx.networkDrive)
  const transfer = new DriveTransfer(config, addressing, () => ctx.networkDrive)
  const target = addressing.targetFor(drivePath('entry'))
  await writeFile(join(workspace, 'entry'), 'local content')
  const observed = await addressing.placementOf(target, undefined)
  expect(observed).toMatchObject({ kind: 'local', info: { type: 'file', size: 13 } })
  await rm(join(workspace, 'entry'))
  await expect(transfer.hydrated(target, 'read', undefined, observed)).rejects.toMatchObject({ code: 'FS_NOT_FOUND' })
  await expect(transfer.diffBasis(target, observed, undefined)).rejects.toMatchObject({ code: 'FS_NOT_FOUND' })
  await expect(readFile(join(remote, 'entry'))).rejects.toMatchObject({ code: 'ENOENT' })
})
