/**
 * Host-for-Client Remote artifact emission: the Remote client module, its
 * mapped declaration file, and the invocation literals both artifacts share.
 */

import { Buffer } from 'node:buffer'
import { posix } from 'node:path'
import { GenMapping, addMapping, toEncodedMap } from '@jridgewell/gen-mapping'
import type { InvocationModel, PackageModel, RemoteBoundaryModel, RemoteTypeImportModel, SymbolId } from './model.ts'
import { TypertEmitError, type RemoteModelEmitResult } from './emitter.ts'
import { TypeGraphRenderer } from './renderer.ts'
import { SchemaArtifact, SchemaEmitter, safeIdentifier, quote, indent, type BoundarySchemaRoot } from './schema-emitter.ts'

/** Emitted local names for imported Remote wire types, keyed by symbol id. */
type ReferenceNames = ReadonlyMap<SymbolId, string>

/** Emit the Remote client contribution for one host package. */
export class RemoteModelEmitter {
  constructor(private readonly renderer: TypeGraphRenderer) {}

  emit(packageModel: PackageModel): RemoteModelEmitResult {
    const schemas = new SchemaEmitter(
      this.renderer,
      [],
      invocationBoundaryRoots(packageModel.invocations),
    ).emit()
    const lines = [
      '/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */',
    ]
    if (schemas.definitions.length > 0) lines.push('import { z } from \'zod\'', '')
    lines.push(...schemas.definitions)
    if (schemas.definitions.length > 0) lines.push('')
    lines.push('export const TYPERT_REMOTE = {')
    lines.push(`  package: ${quote(packageModel.name)},`)
    lines.push('  descriptors: [')
    for (const invocation of packageModel.invocations) {
      lines.push(`${indent(invocationLiteral(invocation, schemas), 4)},`)
    }
    lines.push('  ],')
    lines.push('}')
    lines.push('')
    lines.push('export default TYPERT_REMOTE')
    const declaration = this.renderDts(packageModel)
    return {
      js: `${lines.join('\n')}\n`,
      ...declaration,
    }
  }

  private renderDts(packageModel: PackageModel): Pick<RemoteModelEmitResult, 'dts' | 'dtsMap'> {
    const imports = remoteImports(packageModel.invocations)
    const referenceNames = allocateRemoteImportNames(imports)
    const grouped = new Map<string, { readonly name: string; readonly local: string }[]>()
    for (const imported of imports) {
      const values = grouped.get(imported.specifier) ?? []
      values.push({
        name: imported.name,
        local: referenceNames.get(imported.symbol) as string,
      })
      grouped.set(imported.specifier, values)
    }
    const lines = [
      '/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */',
      'import type {',
      '  RemoteResult,',
      '  TypertRemoteContribution,',
      '} from \'@deepseek-ai/dsh-typert-protocol\'',
    ]
    const sourceMap = new GenMapping({ file: 'typert.remote-client.d.ts' })
    for (const [specifier, values] of [...grouped].sort(([left], [right]) => left.localeCompare(right))) {
      const names = values.sort((left, right) => left.local.localeCompare(right.local)).map(value =>
        value.name === value.local ? value.name : `${value.name} as ${value.local}`)
      lines.push(`import type { ${names.join(', ')} } from ${quote(specifier)}`)
    }
    lines.push('')
    lines.push('declare module \'@deepseek-ai/dsh-typert-protocol\' {')
    const direct = packageModel.invocations.filter(invocation => invocation.invocation.kind === 'direct')
    const scoped = packageModel.invocations.filter(invocation =>
      invocation.invocation.kind === 'context' || invocation.scope !== undefined)
    if (direct.length > 0) {
      for (const namespace of uniqueNamespaces(direct)) {
        lines.push(`  interface ${remoteNamespaceInterface(namespace)} {`)
        for (const invocation of direct.filter(candidate => candidate.namespace === namespace)) {
          this.pushNamespaceSignature(lines, sourceMap, packageModel, invocation, referenceNames)
        }
        lines.push('  }')
      }
      lines.push('  interface TypertRemoteMap {')
      for (const invocation of direct) {
        this.pushSignature(lines, sourceMap, packageModel, invocation, referenceNames, false)
      }
      lines.push('  }')
      lines.push('  interface TypertRemoteNamespaceMap {')
      for (const namespace of uniqueNamespaces(direct)) {
        lines.push(`    ${quote(namespace)}: ${remoteNamespaceInterface(namespace)}`)
      }
      lines.push('  }')
    }
    if (scoped.length > 0) {
      lines.push('  interface TypertRemoteScopeMap {')
      for (const invocation of scoped) {
        this.pushSignature(lines, sourceMap, packageModel, invocation, referenceNames, true)
      }
      lines.push('  }')
    }
    lines.push('}')
    lines.push('')
    lines.push('export declare const TYPERT_REMOTE: TypertRemoteContribution')
    lines.push('export default TYPERT_REMOTE')
    lines.push('//# sourceMappingURL=typert.remote-client.d.ts.map')
    return {
      dts: `${lines.join('\n')}\n`,
      dtsMap: `${JSON.stringify(toEncodedMap(sourceMap))}\n`,
    }
  }

  private pushSignature(
    lines: string[],
    sourceMap: GenMapping,
    packageModel: PackageModel,
    invocation: InvocationModel,
    referenceNames: ReferenceNames,
    scoped: boolean,
  ): void {
    const signature = this.remoteSignature(invocation, referenceNames, scoped)
    const keyLength = signature.indexOf(': (')
    if (keyLength < 0) throw new TypertEmitError(`Remote signature ${invocation.id} has no property delimiter`)
    this.pushMappedSignature(lines, sourceMap, packageModel, invocation, signature, keyLength)
  }

  private pushNamespaceSignature(
    lines: string[],
    sourceMap: GenMapping,
    packageModel: PackageModel,
    invocation: InvocationModel,
    referenceNames: ReferenceNames,
  ): void {
    const key = renderRemotePropertyName(invocation.method)
    const signature = `${key}: ${this.remoteFunctionType(invocation, referenceNames, false)}`
    this.pushMappedSignature(lines, sourceMap, packageModel, invocation, signature, key.length)
  }

  private pushMappedSignature(
    lines: string[],
    sourceMap: GenMapping,
    packageModel: PackageModel,
    invocation: InvocationModel,
    signature: string,
    keyLength: number,
  ): void {
    lines.push(`    ${signature}`)
    const generatedLine = lines.length
    const source = remoteDeclarationSource(packageModel, invocation)
    addMapping(sourceMap, {
      generated: { line: generatedLine, column: 4 },
      source,
      original: { line: invocation.location.line, column: invocation.location.column - 1 },
      name: invocation.method,
    })
    addMapping(sourceMap, {
      generated: { line: generatedLine, column: 4 + keyLength },
    })
  }

  private remoteSignature(
    invocation: InvocationModel,
    referenceNames: ReferenceNames,
    scoped: boolean,
  ): string {
    const context = invocation.invocation.kind === 'context'
      ? invocation.invocation.context
      : invocation.scope?.context
    const key = scoped
      ? `${context as string}:${invocation.namespace}/${invocation.method}`
      : `${invocation.namespace}/${invocation.method}`
    return `${quote(key)}: ${this.remoteFunctionType(invocation, referenceNames, scoped)}`
  }

  private remoteFunctionType(
    invocation: InvocationModel,
    referenceNames: ReferenceNames,
    scoped: boolean,
  ): string {
    const parameters = invocation.parameters.filter(parameter =>
      !scoped || invocation.invocation.kind === 'context' || parameter.wire !== invocation.scope?.wire).map(parameter =>
      `${safeIdentifier(parameter.wire)}${parameter.optional === true ? '?' : ''}: ${this.renderer.renderType(parameter.boundary.type, referenceNames)}`)
    if (invocation.cancellation !== undefined) parameters.push('signal?: AbortSignal')
    const result = this.renderer.renderType(invocation.result.type, referenceNames)
    if (invocation.mode === 'stream') {
      return `(${parameters.join(', ')}) => AsyncIterable<${result}>`
    }
    // The unary Client Remote face delivers the carrier's outcome, so every
    // generated consumer signature resolves to a result the caller reads.
    return `(${parameters.join(', ')}) => Promise<RemoteResult<${result}>>`
  }
}

/**
 * Render one invocation descriptor literal against emitted boundary schemas.
 * @param invocation - modeled Remote invocation.
 * @param schemas - emitted schema artifact carrying boundary codecs.
 * @returns the descriptor's JavaScript object literal.
 */
export function invocationLiteral(invocation: InvocationModel, schemas: SchemaArtifact): string {
  const lines = [
    '{',
    `  id: ${quote(invocation.id)},`,
    `  service: ${quote(invocation.service)},`,
    `  namespace: ${quote(invocation.namespace)},`,
    `  method: ${quote(invocation.method)},`,
  ]
  if (invocation.implementation !== undefined) {
    lines.push(`  implementation: ${quote(invocation.implementation)},`)
  }
  if (invocation.mode !== undefined) lines.push(`  mode: ${quote(invocation.mode)},`)
  if (invocation.invocation.kind === 'direct') {
    lines.push('  invocation: { kind: \'direct\' },')
  } else {
    lines.push('  invocation: {')
    lines.push('    kind: \'context\',')
    lines.push(`    context: ${quote(invocation.invocation.context)},`)
    lines.push(`    wire: ${quote(invocation.invocation.wire)},`)
    lines.push(`    codec: ${indent(strictCodec(
      invocation.invocation.boundary,
      schemas.boundary(contextBoundaryKey(invocation)),
    ), 4).trimStart()},`)
    lines.push('  },')
  }
  if (invocation.scope !== undefined) {
    lines.push('  scope: {')
    lines.push(`    context: ${quote(invocation.scope.context)},`)
    lines.push(`    wire: ${quote(invocation.scope.wire)},`)
    lines.push('  },')
  }
  lines.push('  parameters: [')
  invocation.parameters.forEach((parameter, index) => {
    lines.push('    {')
    lines.push(`      name: ${quote(parameter.name)},`)
    lines.push(`      wire: ${quote(parameter.wire)},`)
    lines.push(`      source: ${quote(parameter.source)},`)
    if (parameter.lookup !== undefined) lines.push(`      lookup: ${quote(parameter.lookup)},`)
    if (parameter.boundary.acceptsUndefined) lines.push('      acceptsUndefined: true,')
    lines.push(`      codec: ${indent(strictCodec(
      parameter.boundary,
      schemas.boundary(parameterBoundaryKey(invocation, index)),
    ), 6).trimStart()},`)
    lines.push('    },')
  })
  lines.push('  ],')
  if (invocation.cancellation !== undefined) {
    lines.push("  cancellation: { parameter: 'signal' },")
  }
  lines.push(`  result: ${indent(strictCodec(
    invocation.result,
    schemas.boundary(resultBoundaryKey(invocation)),
  ), 2).trimStart()},`)
  lines.push(`  sourceLocation: ${JSON.stringify(invocation.location)},`)
  lines.push('}')
  return lines.join('\n')
}

/** Boundary schema roots for every codec an invocation set carries. */
export function invocationBoundaryRoots(invocations: readonly InvocationModel[]): BoundarySchemaRoot[] {
  const result: BoundarySchemaRoot[] = []
  for (const invocation of invocations) {
    if (invocation.invocation.kind === 'context') {
      result.push({ key: contextBoundaryKey(invocation), type: invocation.invocation.boundary.codecType })
    }
    invocation.parameters.forEach((parameter, index) => {
      result.push({ key: parameterBoundaryKey(invocation, index), type: parameter.boundary.codecType })
    })
    result.push({ key: resultBoundaryKey(invocation), type: invocation.result.codecType })
  }
  return result
}

function contextBoundaryKey(invocation: InvocationModel): string {
  return `${invocation.id}:context`
}

function parameterBoundaryKey(invocation: InvocationModel, index: number): string {
  return `${invocation.id}:parameter:${String(index)}`
}

function resultBoundaryKey(invocation: InvocationModel): string {
  return `${invocation.id}:result`
}

function strictCodec(boundary: RemoteBoundaryModel, schema: string): string {
  return [
    '{',
    '  mode: \'strict\',',
    `  typeSymbol: ${quote(boundary.typeSymbol)},`,
    `  schema: ${schema},`,
    '}',
  ].join('\n')
}

function remoteImports(invocations: readonly InvocationModel[]): RemoteTypeImportModel[] {
  const imports = new Map<SymbolId, RemoteTypeImportModel>()
  const add = (boundary: RemoteBoundaryModel): void => {
    for (const imported of boundary.imports) {
      const current = imports.get(imported.symbol)
      if (current !== undefined
        && (current.specifier !== imported.specifier || current.name !== imported.name)) {
        throw new TypertEmitError(`typert Remote emitter: symbol ${imported.symbol} has inconsistent public imports`)
      }
      imports.set(imported.symbol, imported)
    }
  }
  for (const invocation of invocations) {
    if (invocation.invocation.kind === 'context') add(invocation.invocation.boundary)
    for (const parameter of invocation.parameters) add(parameter.boundary)
    add(invocation.result)
  }
  return [...imports.values()].sort((left, right) =>
    left.specifier.localeCompare(right.specifier) || left.name.localeCompare(right.name))
}

function allocateRemoteImportNames(imports: readonly RemoteTypeImportModel[]): ReadonlyMap<SymbolId, string> {
  const used = new Set(['TypertRemoteContribution', 'TYPERT_REMOTE'])
  const names = new Map<SymbolId, string>()
  for (const imported of imports) {
    const base = safeIdentifier(imported.name)
    let name = base
    let suffix = 2
    while (used.has(name)) name = `${base}$remote${String(suffix++)}`
    used.add(name)
    names.set(imported.symbol, name)
  }
  return names
}

function remoteDeclarationSource(packageModel: PackageModel, invocation: InvocationModel): string {
  const relativeSource = posix.relative(packageModel.root, invocation.location.file)
  if (relativeSource === '' || relativeSource === '..' || relativeSource.startsWith('../') || posix.isAbsolute(relativeSource)) {
    throw new TypertEmitError(
      `Remote declaration ${invocation.id} is outside its package root ${packageModel.root}`,
    )
  }
  return posix.join('..', relativeSource)
}

function uniqueNamespaces(invocations: readonly InvocationModel[]): string[] {
  return [...new Set(invocations.map(invocation => invocation.namespace))].sort()
}

function remoteNamespaceInterface(namespace: string): string {
  return `TypertRemoteNamespace$${Buffer.from(namespace, 'utf8').toString('hex')}`
}

function renderRemotePropertyName(name: string): string {
  return /^[$A-Z_a-z][$\w]*$/u.test(name) ? name : quote(name)
}
