import { readFile } from 'node:fs/promises'
import { chromium, webkit, type Browser, type Locator, type Page } from 'playwright'
import { afterAll, beforeAll, describe, expect, it, onTestFailed } from 'vitest'
import AxeBuilder from '@axe-core/playwright'
import { SessionId } from '@deepseek-ai/dsh-session'
import { launchWebScaffold, seedSession, type WebScaffold } from './scaffold.ts'

const sourceId = SessionId('sidebar-source')
const unavailableId = SessionId('sidebar-unavailable')
const recording = new URL('../../../snapshots/web/seeded-history/session.jsonl', import.meta.url)

describe.each([
  { name: 'Chromium', engine: chromium },
  { name: 'WebKit', engine: webkit },
])('sidebar session actions in $name', ({ engine }) => {
  let scaffold: WebScaffold
  let browser: Browser
  let page: Page
  let secondaryGesture: Parameters<Locator['click']>[0]
  const consoleErrors: string[] = []
  const pageErrors: string[] = []

  beforeAll(async () => {
    scaffold = await launchWebScaffold()
    const history = await readFile(recording, 'utf8')
    await seedSession(scaffold, history, sourceId)
    await seedSession(scaffold, history, unavailableId, 'removed-preset')
    const workspace = await scaffold.ctx.workspaceRegistry.create(scaffold.workspaceCwd)
    await workspace.attachSession(sourceId)
    await workspace.attachSession(unavailableId)
    browser = await engine.launch()
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, locale: 'en-US' })
    page = await context.newPage()
    page.setDefaultTimeout(5_000)
    secondaryGesture = await page.evaluate(() => navigator.platform.startsWith('Mac') || navigator.platform.startsWith('iP'))
      ? { modifiers: ['Control'] }
      : { button: 'right' }
    page.on('console', (message) => {
      if (message.type() === 'error' || message.type() === 'warning') consoleErrors.push(message.text())
    })
    page.on('pageerror', error => pageErrors.push(String(error)))
    await page.goto(scaffold.authenticatedUrl, { waitUntil: 'load' })
    const group = page.getByRole('treeitem').first()
    await group.waitFor()
    await group.press('ArrowRight')
    await page.locator(`[data-row-key="session:${sourceId}"]`).waitFor()
  }, 120_000)

  afterAll(async () => {
    await browser?.close()
    await scaffold?.close()
    expect(consoleErrors).toEqual([])
    expect(pageErrors).toEqual([])
  })

  it('keeps the requested menu open across repeated sidebar context gestures', async () => {
    onTestFailed(async () => { await page.screenshot({ path: `.artifacts/finish/sidebar-context-failure-${engine.name()}.png` }) })
    const row = page.locator(`[data-row-key="session:${sourceId}"]`)
    await row.click()
    const group = page.getByRole('treeitem').first()
    const expanded = await group.getAttribute('aria-expanded')
    const current = await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')
    await group.click({ button: 'right', position: { x: 100, y: 16 } })
    await page.getByRole('menuitem', { name: 'Delete workspace' }).waitFor({ timeout: 5_000 })
    await row.click({ button: 'right', position: { x: 40, y: 16 } })
    await page.getByRole('menuitem', { name: 'Fork session' }).waitFor({ timeout: 5_000 })
    expect(await page.getByRole('menu').count()).toBe(1)
    await page.keyboard.press('Escape')
    await page.getByRole('menu').waitFor({ state: 'hidden' })
    await row.click({ ...secondaryGesture, position: { x: 100, y: 16 } })
    await page.getByRole('menuitem', { name: 'Fork session' }).waitFor({ timeout: 5_000 })
    await page.keyboard.press('Escape')
    await page.getByRole('menu').waitFor({ state: 'hidden' })
    const actions = row.getByRole('button', { name: /Session actions/ })
    await actions.click(secondaryGesture)
    await page.getByRole('menuitem', { name: 'Fork session' }).waitFor({ timeout: 5_000 })
    await page.keyboard.press('Escape')
    await page.getByRole('menu').waitFor({ state: 'hidden' })
    await group.click({ ...secondaryGesture, position: { x: 100, y: 16 } })
    await page.getByRole('menuitem', { name: 'Delete workspace' }).waitFor({ timeout: 5_000 })
    await page.keyboard.press('Escape')
    await page.getByRole('menu').waitFor({ state: 'hidden' })
    const workspaceActions = group.getByRole('button', { name: /Workspace actions/ })
    await workspaceActions.click(secondaryGesture)
    await page.getByRole('menuitem', { name: 'Delete workspace' }).waitFor({ timeout: 5_000 })
    expect(await group.getAttribute('aria-expanded')).toBe(expanded)
    expect(await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')).toBe(current)
    await page.keyboard.press('Escape')
    await page.getByRole('menu').waitFor({ state: 'hidden' })
    await workspaceActions.click()
    await page.getByRole('menuitem', { name: 'Delete workspace' }).waitFor({ timeout: 5_000 })
    await workspaceActions.click()
    await page.getByRole('menu').waitFor({ state: 'hidden' })
    await row.hover()
    await actions.click()
    await page.getByRole('menuitem', { name: 'Fork session' }).waitFor({ timeout: 5_000 })
    await actions.click()
    await page.getByRole('menu').waitFor({ state: 'hidden' })
    await row.click({ button: 'right', position: { x: 40, y: 16 } })
    await page.getByRole('menuitem', { name: 'Fork session' }).waitFor({ timeout: 5_000 })
    await page.getByRole('textbox', { name: 'Message' }).click()
    await page.getByRole('menu').waitFor({ state: 'hidden' })
  }, 20_000)

  it('reserves the workspace create button secondary press for its menu', async () => {
    onTestFailed(async () => { await page.screenshot({ path: `.artifacts/finish/sidebar-create-failure-${engine.name()}.png` }) })
    const row = page.locator(`[data-row-key="session:${sourceId}"]`)
    await row.click()
    const group = page.getByRole('treeitem').first()
    const expanded = await group.getAttribute('aria-expanded')
    const current = await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')
    const count = await page.getByRole('treeitem').count()
    await group.hover()
    await group.getByRole('button', { name: /New session in/ }).click(secondaryGesture)
    await page.getByRole('menuitem', { name: 'Delete workspace' }).waitFor()
    expect(await group.getAttribute('aria-expanded')).toBe(expanded)
    expect(await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')).toBe(current)
    expect(await page.getByRole('treeitem').count()).toBe(count)
    await page.keyboard.press('Escape')
    await page.getByRole('menu').waitFor({ state: 'hidden' })
  })

  it('keeps context and keyboard menus available while the pointer moves', async () => {
    onTestFailed(async () => { await page.screenshot({ path: `.artifacts/finish/sidebar-persistence-failure-${engine.name()}.png` }) })
    const session = page.locator(`[data-row-key="session:${sourceId}"]`)
    await session.click()
    const group = page.getByRole('treeitem').first()
    for (const row of [group, session]) {
      await row.click({ button: 'right', position: { x: 100, y: 16 } })
      const menu = page.getByRole('menu')
      await menu.waitFor()
      await menu.hover({ position: { x: 10, y: 10 } })
      await row.hover({ position: { x: 20, y: 16 } })
      await page.waitForTimeout(300)
      expect(await menu.isVisible()).toBe(true)
      await page.keyboard.press('Escape')
      await menu.waitFor({ state: 'hidden' })
      const actions = row.getByRole('button', { name: /actions for/ })
      await actions.focus()
      await page.keyboard.press('Enter')
      await menu.waitFor()
      expect(await menu.getByRole('menuitem').first().evaluate(element => element === document.activeElement)).toBe(true)
      await menu.hover({ position: { x: 10, y: 10 } })
      await page.mouse.move(1400, 20)
      await page.waitForTimeout(300)
      expect(await menu.isVisible()).toBe(true)
      await page.keyboard.press('Escape')
      await menu.waitFor({ state: 'hidden' })
      expect(await actions.evaluate(element => element === document.activeElement)).toBe(true)
      await page.keyboard.press('Space')
      await menu.waitFor()
      await page.keyboard.press('Escape')
      await menu.waitFor({ state: 'hidden' })
    }
  })

  it('hands focus from keyboard row menus to their Rename dialogs', async () => {
    const session = page.locator(`[data-row-key="session:${sourceId}"]`)
    const group = page.getByRole('treeitem').first()
    const inertCount = await page.locator('[inert]').count()
    for (const row of [group, session, group, session]) {
      await row.focus()
      await row.getByRole('button', { name: /actions for/ }).press('Enter')
      const rename = page.getByRole('menuitem', { name: 'Rename', exact: true })
      await rename.waitFor()
      await rename.press('Enter')
      const dialog = page.getByRole('dialog')
      const input = dialog.getByRole('textbox')
      await input.waitFor()
      expect(await input.evaluate(element => document.activeElement === element)).toBe(true)
      expect(await page.getByRole('menu').count()).toBe(0)
      await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
      await dialog.waitFor({ state: 'hidden' })
      expect(await page.evaluate(() => document.body.inert)).toBe(false)
      expect(await page.locator('[inert]').count()).toBe(inertCount)
      expect(await row.isVisible()).toBe(true)
    }
  })

  it('positions the right-click menu and commits Rename and Fork through the host', async () => {
    const row = page.locator(`[data-row-key="session:${sourceId}"]`)
    await row.click()
    await row.click({ button: 'right', position: { x: 100, y: 16 } })
    const menu = page.getByRole('menu')
    await menu.waitFor()
    const rowBox = await row.boundingBox()
    const menuBox = await menu.boundingBox()
    if (rowBox === null || menuBox === null) throw new Error('session menu has no layout box')
    expect(menuBox.x).toBeCloseTo(rowBox.x + 100, 0)
    expect(menuBox.y).toBeCloseTo(rowBox.y + 20, 0)
    expect(menuBox.x + menuBox.width).toBeLessThanOrEqual(1440)
    expect(menuBox.y + menuBox.height).toBeLessThanOrEqual(1000)
    const menuAudit = await new AxeBuilder({ page }).analyze()
    expect(menuAudit.violations).toEqual([])
    expect(menuAudit.incomplete).toEqual([])
    await page.screenshot({ path: `.artifacts/finish/sidebar-menu-${engine.name()}.png` })
    await menu.getByRole('menuitem', { name: 'Rename', exact: true }).click()
    const rename = page.getByRole('dialog', { name: 'Rename session' })
    await rename.getByRole('textbox', { name: 'Session name' }).fill('Sidebar verification')
    await page.screenshot({ path: `.artifacts/finish/sidebar-rename-${engine.name()}.png` })
    await rename.getByRole('button', { name: 'Rename', exact: true }).click()
    await rename.waitFor({ state: 'hidden' })
    await expect.poll(() => row.textContent()).toContain('Sidebar verification')
    await row.click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Fork session' }).click()
    await expect.poll(() => scaffold.ctx.agents.list().filter(
      agent => agent.session.header.parentSession === sourceId,
    ).length).toBe(1)
    const child = scaffold.ctx.agents.list().find(agent => agent.session.header.parentSession === sourceId)
    if (child === undefined) throw new Error('fork did not publish a child session')
    const childRow = page.locator(`[data-row-key="session:${child.session.id}"]`)
    await expect.poll(() => childRow.getAttribute('aria-current')).toBe('true')
    await expect.poll(() => childRow.textContent()).toContain('Sidebar verification (1)')
    await page.screenshot({ path: `.artifacts/finish/sidebar-fork-${engine.name()}.png` })
  })

  it('shows a preset failure without changing the current conversation', async () => {
    const current = await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')
    const row = page.locator(`[data-row-key="session:${unavailableId}"]`)
    await row.click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Fork session' }).click()
    const error = page.getByRole('dialog', { name: 'Couldn’t fork session' })
    await error.waitFor()
    const errorAudit = await new AxeBuilder({ page }).analyze()
    expect(errorAudit.violations).toEqual([])
    expect(errorAudit.incomplete).toEqual([])
    expect(await error.getByRole('alert').textContent()).toContain('removed-preset')
    expect(await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')).toBe(current)
    expect(scaffold.ctx.agents.list().some(agent => agent.session.header.parentSession === unavailableId)).toBe(false)
    await page.screenshot({ path: `.artifacts/finish/sidebar-fork-error-${engine.name()}.png` })
    await error.getByRole('button', { name: 'Close', exact: true }).click()
    await error.waitFor({ state: 'hidden' })
  })

  it('retains the rename draft and displays the host refusal', async () => {
    const current = await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')
    const row = page.locator(`[data-row-key="session:${unavailableId}"]`)
    const title = await row.textContent()
    await row.click({ button: 'right' })
    await page.getByRole('menuitem', { name: 'Rename', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Rename session' })
    const input = dialog.getByRole('textbox', { name: 'Session name' })
    await input.fill('Retained rename draft')
    await dialog.getByRole('button', { name: 'Rename', exact: true }).click()
    await dialog.getByRole('alert').waitFor()
    expect(await dialog.getByRole('alert').textContent()).toContain('removed-preset')
    expect(await input.inputValue()).toBe('Retained rename draft')
    expect(await row.textContent()).toBe(title)
    expect(await page.locator('[role="treeitem"][aria-current="true"]').getAttribute('data-row-key')).toBe(current)
    const audit = await new AxeBuilder({ page }).analyze()
    expect(audit.violations).toEqual([])
    expect(audit.incomplete).toEqual([])
    await page.screenshot({ path: `.artifacts/finish/sidebar-rename-error-${engine.name()}.png` })
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click()
    await dialog.waitFor({ state: 'hidden' })
  })
})
