/**
 * Markdown rendering for the plugin config catalog.
 */

import { LINK_MAP } from './gen-cordis-catalog.ts'
import { githubSlug } from './verify-md-links.ts'
import type { CatalogEntry, TypeRef } from './gen-config-catalog-model.ts'

const FENCE = 'ts config-catalog'

function requiresLine(inject: string[]): string {
  return inject.length ? `Requires: ${inject.map(k => `\`${k}\``).join(' · ')}` : ''
}

function refLink(ref: TypeRef, byName: Map<string, CatalogEntry>): string {
  const target = byName.get(ref.specifier)
  if (target?.kind === 'config' && ref.imported === target.configTypeName) {
    return `[\`${ref.alias}\`](#${githubSlug(target.pkg)})`
  }
  const page = LINK_MAP[ref.imported]
  if (page) return `[\`${ref.alias}\`](subsystems/${page})`
  if (target) return `[\`${ref.alias}\`](../${target.entry})`
  return `\`${ref.alias}\` (\`${ref.specifier}\`)`
}

function renderConfigEntry(entry: CatalogEntry, byName: Map<string, CatalogEntry>): string[] {
  const out = [`<a id="${githubSlug(entry.pkg)}"></a>`, '', `## \`${entry.pkg}\``, '']
  const requires = requiresLine(entry.inject)
  if (requires) out.push(requires, '')
  out.push('```' + FENCE, ...(entry.pastes ?? []).map(p => p.text).join('\n\n').split('\n'), '```', '')
  if (entry.refs && entry.refs.length > 0) {
    out.push(`Depends on: ${entry.refs.map(r => refLink(r, byName)).join(' · ')}`, '')
  }
  const source = entry.pastes?.[0]?.source ?? entry.entry
  out.push(`Source: [\`${source}\`](../${source.split(':')[0]})`, '')
  return out
}

function renderTerse(entry: CatalogEntry, detail: string): string {
  const requires = entry.inject.length ? ` — requires ${entry.inject.map(k => `\`${k}\``).join(' · ')}` : ''
  return `- \`${entry.pkg}\`${detail}${requires} ([\`${entry.entry}\`](../${entry.entry}))`
}

/** Render the full catalog (pure, deterministic given sorted entries). */
export function renderCatalog(entries: CatalogEntry[]): string {
  const byName = new Map(entries.map(e => [e.pkg, e]))
  const lines: string[] = [
    '<!-- Generated by scripts/gen-config-catalog.ts — do not edit by hand.',
    '     Run `bun run gen-config-catalog` to regenerate. -->',
    '',
    '# Plugin Config Catalog',
    '',
    'Every `config:` block a `cordis.yml` entry can set: for each loadable harness package, the verbatim config declaration (JSDoc included) its `apply` function or service constructor receives, with every referenced type pasted alongside (package-local types) or linked (everything else). The paste is the plugin\'s full declared config type — a field the runtime schema deliberately excludes is a runtime-only seam (its own JSDoc says so) and is not settable from `cordis.yml`. This is the **deployment**-axis reference — the wiring a plugin author works against is the generated Cordis API region on each [subsystem page](subsystems/core.md), the model-facing tool schemas are the [tool catalog](tool-catalog.md), and [subsystems/](subsystems/core.md) documents the types these declarations reference.',
    '',
    'This file is GENERATED from source (`scripts/gen-config-catalog.ts`) and verified fresh by `bun run verify-config-catalog` (part of `doc-sync`) — do not edit it by hand. Declaration blocks use a `ts config-catalog` fence (skipped by doc-typecheck, since a lone declaration referencing imports is not standalone-compilable). The generator also cross-checks the runtime schemastery schema against the pasted declaration — every schema-validated key, nested keys included, must be locatable on the declared config type — so the paste cannot hide a loader-accepted field.',
    '',
    'A `Requires:` line lists the service keys the plugin `inject`s: its `cordis.yml` tree must also load providers for those services. Scope is the harness tier (`packages/`); the vendored cordis plugins a config tree may also load (`hmr`, the console logger, …) are pinned upstream source ([vendoring policy](../vendor/README.md)) and not catalogued here.',
    '',
  ]
  for (const entry of entries.filter(e => e.kind === 'config')) {
    lines.push(...renderConfigEntry(entry, byName))
  }
  lines.push(
    '## Loadable plugins with no config',
    '',
    'These load from a `cordis.yml` entry with no `config:` block; they declare no configuration API.',
    '',
    ...entries.filter(e => e.kind === 'no-config').map(e => renderTerse(e, '')),
    '',
    '## Seam packages (not directly loadable)',
    '',
    'Abstract service classes — a deployment loads a concrete implementation package instead ([capability seams](../.agents/notes/implemented/architecture/2026-06-13-capability-seams.md)).',
    '',
    ...entries.filter(e => e.kind === 'seam').map(e => renderTerse(e, ` — abstract \`${e.className ?? ''}\``)),
    '',
    '## Library packages (no plugin entry)',
    '',
    'Imported as libraries by other packages; a `cordis.yml` cannot load them.',
    '',
    ...entries.filter(e => e.kind === 'library').map(e => renderTerse(e, '')),
    '',
  )
  return lines.join('\n')
}
