/**
 * Generate `docs/persistence-catalog.md` from every `SessionEventMap` merge and
 * the owning event-envelope types. This is the durable-record vocabulary, not
 * the live Cordis bus. `--check` verifies the artifact.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { githubSlug } from './verify-md-links.ts'
import {
  annotateSurface as annotateSurfaceScan,
  collectEventEnvelopeTypes as collectEnvelopeTypesScan,
  collectLogEvents as collectLogEventsScan,
  collectSurfaceEventTypes as collectSurfaceTypesScan,
  type AnnotatedLogEventEntry as AnnotatedEntry,
  type EventEnvelopeTypeEntry as EnvelopeEntry,
  type LogEventEntry as LogEntry,
} from './gen-persistence-catalog-scan.ts'

export type AnnotatedLogEventEntry = AnnotatedEntry
export type EventEnvelopeTypeEntry = EnvelopeEntry
export type LogEventEntry = LogEntry

/** @see {@link ./gen-persistence-catalog-scan.ts} */
export function collectLogEvents(scanRoot?: string) {
  return collectLogEventsScan(scanRoot)
}

/** @see {@link ./gen-persistence-catalog-scan.ts} */
export function collectEventEnvelopeTypes(scanRoot?: string) {
  return collectEnvelopeTypesScan(scanRoot)
}

/** @see {@link ./gen-persistence-catalog-scan.ts} */
export function collectSurfaceEventTypes(scanRoot?: string) {
  return collectSurfaceTypesScan(scanRoot)
}

/** @see {@link ./gen-persistence-catalog-scan.ts} */
export function annotateSurface(events: LogEventEntry[], surfaceTypes: string[]) {
  return annotateSurfaceScan(events, surfaceTypes)
}

const root = resolve(import.meta.dirname, '..')
const OUT = 'docs/persistence-catalog.md'
const OUT_RUNTIME_TYPES = 'packages/core/session/src/known-event-types.ts'
const FENCE = 'ts persistence-catalog'

const LINK_MAP: Record<string, string> = {
  ToolCallId: 'subsystems/core.md',
  ContentBlock: 'subsystems/core.md',
  MessageSource: 'subsystems/core.md',
  ScheduleChange: 'subsystems/schedule.md',
  StreamChunk: 'subsystems/llm-streaming.md',
  TokenUsage: 'subsystems/llm-streaming.md',
  TodoItem: 'subsystems/todo.md',
  TurnTrigger: 'subsystems/session.md',
  TurnEndReason: 'subsystems/session.md',
  ApprovalAdversaryRequestEventData: 'subsystems/approval.md',
  SessionTitleEventData: 'subsystems/session-title.md',
  SessionTitleLlmRequestEventData: 'subsystems/session-title.md',
  SessionTitleModelProvenance: 'subsystems/session-title.md',
  SessionTitleProviderId: 'subsystems/session-title.md',
  SessionTitleSource: 'subsystems/session-title.md',
  TeamId: 'subsystems/agent-team.md',
  TeamMemberSnapshot: 'subsystems/agent-team.md',
  TeamMessageId: 'subsystems/agent-team.md',
  TeamMessageSnapshot: 'subsystems/agent-team.md',
  TeamTaskSnapshot: 'subsystems/agent-team.md',
}

function typeLinks(payload: string): string {
  const seen = new Set<string>()
  for (const name of Object.keys(LINK_MAP)) {
    if (new RegExp(`\\b${name}\\b`).test(payload)) seen.add(name)
  }
  if (seen.size === 0) return ''
  const links = [...seen].sort().map(n => `[${n}](${LINK_MAP[n]})`)
  return `Types: ${links.join(' · ')}`
}

function renderEvent(e: AnnotatedLogEventEntry): string[] {
  const heading = `${e.name} — ${e.surface ? 'surface' : 'log-only'}`
  const out = [`<a id="${githubSlug(heading)}"></a>`, '', `#### \`${e.name}\` — ${e.surface ? 'surface' : 'log-only'}`, '']
  out.push('```' + FENCE, e.declaration, '```', '')
  const links = typeLinks(e.payload)
  if (links) out.push(links, '')
  out.push(`Source: [\`${e.source}\`](../${e.source.split(':')[0]})`, '')
  return out
}

/** Render the full catalog. */
export function render(events: AnnotatedLogEventEntry[], envelopeTypes: EventEnvelopeTypeEntry[]): string {
  const lines: string[] = [
    '<!-- Generated by scripts/gen-persistence-catalog.ts — do not edit by hand.',
    '     Run `bun run gen-persistence-catalog` to regenerate. -->',
    '',
    '# Session Persistence Event Catalog',
    '',
    'Every event type that can appear in a session\'s durable event log: the complete persisted `SessionEvent` envelope and each member of the merge-extensible `SessionEventMap` — the owning vocabulary in `@deepseek-ai/dsh-session` plus every plugin declaration merge into `@deepseek-ai/dsh-session/types` in this repo — with source JSDoc, full payload declaration, surface badge, and declaration site. It complements [session.md](subsystems/session.md) (surface ordering and the `deriveMessages()` projection), [persistence.md](subsystems/persistence.md) (how the log is made durable), and the generated region of [session.md](subsystems/session.md#cordis-surface) (the live bus wiring — a log event is NOT a cordis event; it reaches listeners via the single `session/event` emit).',
    '',
    'This file is GENERATED from source (`scripts/gen-persistence-catalog.ts`) and verified fresh by `bun run verify-persistence-catalog` (part of `doc-sync`) — do not edit it by hand. Declaration blocks retain the source declaration and nested property JSDoc, removing only the indentation imposed by a containing interface/module, and use a `ts persistence-catalog` fence (skipped by doc-typecheck because declarations reference types from their owning modules). Type names in a payload link to the page that documents them. See [the persistence-log-catalog Agent Note](../.agents/notes/archived/process/2026-07-04-persistence-log-catalog.md).',
    '',
    'The envelope declarations below compose each event\'s `type`, monotonic `seq`, epoch-ms `time`, `data`, and the conditional `surfaceOp`/`sourceEventSeqs` fields. **surface** marks a `SurfaceEventType` member: it produces an LLM message and declares how it joins the surface list. **log-only** marks everything else: a durable, replayable record with no derived-history contribution. Every payload is JSON-serializable (enforced at `Session.append`), and the whole format is pinned at `SESSION_FORMAT_VERSION = 0` — pre-release, no compatibility implied ([the version stance](subsystems/persistence.md)). Scope: the packages in this repo; a downstream plugin can merge further event types, which are outside this catalog by construction.',
    '',
    '## Event envelope',
    '',
    '```' + FENCE,
    envelopeTypes.map(entry => entry.declaration).join('\n\n'),
    '```',
    '',
    `Sources: ${envelopeTypes.map(entry => `[\`${entry.source}\`](../${entry.source.split(':')[0]})`).join(' · ')}`,
    '',
    '## Events',
    '',
  ]
  const scopes = [...new Set(events.map(e => e.scope))].sort()
  for (const scope of scopes) {
    lines.push(`### \`${scope}/*\``, '')
    for (const e of events.filter(x => x.scope === scope).sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(...renderEvent(e))
    }
  }
  return lines.join('\n')
}

/** Render the runtime known-vocabulary module. */
export function renderKnownEventTypes(events: AnnotatedLogEventEntry[]): string {
  const names = [...new Set(events.map(e => e.name))].sort()
  return [
    '/**',
    ' * GENERATED by `scripts/gen-persistence-catalog.ts` — do not edit by hand; run',
    ' * `bun run gen-persistence-catalog` to regenerate (verified fresh by',
    ' * `bun run verify-persistence-catalog`, part of `doc-sync`).',
    ' * @module @deepseek-ai/dsh-session/known-event-types',
    ' */',
    '',
    '/**',
    ' * Every `SessionEventMap` member declared in this repository — the event',
    ' * vocabulary this build understands. The persistence read path refuses to',
    ' * interpret a log containing a type outside this set: such a log was likely',
    ' * written by a newer harness, and silently skipping the event could',
    ' * reconstruct a wrong session.',
    ' * Downstream (out-of-repo) plugin events are outside this list by',
    ' * construction; a registration surface for them is deferred until such a',
    ' * consumer exists.',
    ' */',
    'export const KNOWN_SESSION_EVENT_TYPES: ReadonlySet<string> = new Set([',
    ...names.map(name => `  '${name}',`),
    '])',
    '',
  ].join('\n')
}

function main() {
  const events = annotateSurface(collectLogEvents(), collectSurfaceEventTypes())
  const artifacts = [
    { out: OUT, content: render(events, collectEventEnvelopeTypes()) },
    { out: OUT_RUNTIME_TYPES, content: renderKnownEventTypes(events) },
  ]
  if (process.argv.includes('--check')) {
    const stale = artifacts.filter((artifact) => {
      const path = resolve(root, artifact.out)
      const committed = existsSync(path) ? readFileSync(path, 'utf8') : null
      return committed !== artifact.content
    })
    if (stale.length === 0) {
      process.stdout.write(`gen-persistence-catalog: ${artifacts.map(a => a.out).join(', ')} are up to date.\n`)
      process.exit(0)
    }
    process.stderr.write(`gen-persistence-catalog: ${stale.map(a => a.out).join(', ')} stale. Run \`bun run gen-persistence-catalog\` and commit the result.\n`)
    process.exit(1)
  }
  for (const artifact of artifacts) {
    writeFileSync(resolve(root, artifact.out), artifact.content)
    process.stdout.write(`gen-persistence-catalog: wrote ${artifact.out}.\n`)
  }
}

if (process.argv[1] !== undefined && import.meta.filename === resolve(process.argv[1])) {
  main()
}
