/** Suites requiring serial process isolation within the complete Vitest run. */
export const processBoundTests = [
  'packages/session/session-persistence-jsonl/tests/jsonl.spec.ts',
  'packages/subagent/subagent-acp/tests/subagent-acp.spec.ts',
  'packages/subagent/subagent-codex/tests/real-product.spec.ts',
  'packages/subprocess/subprocess-local/tests/process-exit.spec.ts',
  'packages/subprocess/subprocess-local/tests/spawn.spec.ts',
  'packages/subprocess/subprocess-local/tests/spawn-env.spec.ts',
  'packages/subprocess/subprocess-local/tests/spawn-output.spec.ts',
  'packages/subprocess/subprocess-local/tests/spawn-tree.spec.ts',
  'packages/context/time-context/tests/time-context.spec.ts',
  'packages/boot/app-boot/tests/app-boot.spec.ts',
  'packages/workflow/workflow-worker-thread/tests/session.spec.ts',
  'packages/boot/app-boot/tests/user-patches.spec.ts',
  'packages/shell/tool-shell-persistent/tests/bash-loader-composition.spec.ts',
  'packages/terminal/terminal-bash/tests/local.spec.ts',
  'scripts/client-build-environment.client.spec.ts',
  // The installer changes repository-global hook configuration.
  'scripts/install-lefthook.spec.ts',
  'scripts/release/integration-source.spec.ts',
  'scripts/lint-scope-corpus.spec.ts',
  'packages/boot/app-boot/tests/hmr-config.spec.ts',
  'packages/session/session-projection-cache/tests/cache.spec.ts',
  'packages/experimental/inspector/tests/integration.host.spec.ts',
]
